# Generated by Django 4.0.3 on 2022-03-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_signaturerequestuser_signature_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerequestuser',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
