# Generated by Django 4.0.3 on 2022-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_signaturerequestuser_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid_image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
