# Generated by Django 4.0.3 on 2022-03-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_file_uuid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid_image',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='base_app.file'),
        ),
    ]
